<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Software;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class SoftwareSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('software')->insert([
            
            //SAM 7 for Windows
            [
                'name' => 'SAM 7 for Windows',
                'function' => 'SAM 7 for Windows is a software solution designed to streamline asset management and tracking processes. It provides organizations with tools to effectively monitor, manage, and report on their physical and digital assets.',
                'version' => '2023.12.1',
                'editor' => 'NREL',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0107684',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-06-19',
                'update_date' => '2024-06-19',
                'responsable_cit' => 'Ahmad Amine EL AOURI',
                'adm' => 'Ahmad Amine EL AOURI',
                'mot_clef' => 'SAM 7 for Windows - NREL',
                'category_id' => 3,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'Francais, Anglais',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'SAM 7',
                'exe_file_path' => 'SAM7Setup.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Simple',
                'prerequis' => 'Only computer with Windows',
                'created_at' => '2024-06-19',
                'euc'=>'Ahmad Amine EL AOURI',
                'kb_num'=>'KB0044639',
                'comment'=>' ',
            ],
            //HQ-OSE
            [
                'name' => 'HQ-OSE',
                'function' => 'HQ-OSE is a comprehensive software solution designed to streamline and enhance the operational processes of organizations.',
                'version' => 'v4.1',
                'editor' => 'HydroQuebec',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0107684',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-06-18',
                'update_date' => '2024-06-18',
                'responsable_cit' => 'Ahmad Amine EL AOURI',
                'adm' => 'Ahmad Amine EL AOURI',
                'mot_clef' => 'HQ-OSE - HydroQuebec',
                'category_id' => 4,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10, Android, iOS',
                'languages' => 'Francais, Anglais',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'HQ-OSE',
                'exe_file_path' => 'HQSetup.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Complexe',
                'prerequis' => '',
                'created_at' => '2024-06-18',
                'euc'=>'Ahmad Amine EL AOURI',
                'kb_num'=>'KB0044640',
                'comment'=>' ',
            ],
            //WIRESHARK
            [
                'name' => 'wireshark',
                'function' => 'Wireshark is an open-source network protocol analyzer used for network troubleshooting, analysis, and protocol development.',
                'version' => '4.2.5.0',
                'editor' => 'GeraldCombs',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0108003',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-06-20',
                'update_date' => '2024-06-20',
                'responsable_cit' => 'Ahmad Amine EL AOURI',
                'adm' => 'Ahmad Amine EL AOURI',
                'mot_clef' => 'wireshark',
                'category_id' => 1,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10, Android, iOS',
                'languages' => 'English',
                'master_integration' => true,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'wireshark',
                'exe_file_path' => 'wiresharkSetup.exe',
                'complexity' => 'Moyen',
                'criticite' => 'moyen',
                'prerequis' => 'Limited for iOS and Android.',
                'created_at' => '2024-06-20',
                'euc'=>'Ahmad Amine EL AOURI',
                'kb_num'=>'KB0044189',
                'comment'=>' ',
            ],
            //MS TEAMS
            [
                'name' => 'Ms teams ',
                'function' => 'Microsoft Teams is part of the Microsoft 365 and is a collaboration platform that combines workplace chat, meetings, file storage, and application integration.',
                'version' => 'v1.4.00.4167',
                'editor' => 'Microsoft',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0108001',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-07-16',
                'update_date' => '2024-07-16',
                'responsable_cit' => 'Ahmad Amine EL AOURI',
                'adm' => 'Ahmad Amine EL AOURI',
                'mot_clef' => 'MS teams',
                'category_id' => 4,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10, Android, iOS',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'MS teams',
                'exe_file_path' => 'MSSetup.exe',
                'complexity' => 'Simple',
                'criticite' => 'Simple',
                'prerequis' => '',
                'created_at' => '2024-07-16',
                'euc'=>'Ahmad Amine EL AOURI',
                'kb_num'=>'KB0046465',
                'comment'=>'RITM0110883  créer afin de deployer via centre Admin Teams.',
            ],
            //SAP GUI
            [
                'name' => 'SAP GUI',
                'function' => 'The SAP GUI provides users with a graphical interface for accessing SAPs modules, applications, and services. It allows users to enter and retrieve data from SAP ERP systems, and supports the execution of reports, data entry, and various tasks within the SAP ecosystem.',
                'version' => 'v8 patch 4',
                'editor' => 'SAP',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => ' ',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-07-16',
                'update_date' => '2024-07-16',
                'responsable_cit' => 'Ahmad Amine EL AOURI',
                'adm' => 'Ahmad Amine EL AOURI',
                'mot_clef' => 'SAP - GUI',
                'category_id' => 1,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'SAP GUI',
                'exe_file_path' => 'SAPSetup.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Simple',
                'prerequis' => '',
                'created_at' => '2024-07-16',
                'euc'=>'Ahmad Amine EL AOURI',
                'kb_num'=>'KB0046464',
                'comment'=>' ',
            ],
            //POWERSHELL
            [
                'name' => 'Powershell',
                'function' => 'Powershell is designed to help IT professionals and system administrators automate and manage administrative tasks and configuration management.',
                'version' => '7.4.3',
                'editor' => 'powerShell',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0109835',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-07-26',
                'update_date' => '2024-07-26',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'Powershell',
                'category_id' => 1,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'manually',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'Powershell',
                'exe_file_path' => 'PowershellSetup.exe',
                'complexity' => 'Simple',
                'criticite' => 'Simple',
                'prerequis' => ' ',
                'created_at' => '2024-07-26',
                'euc'=>'Ahmad Amine EL AOURI',
                'kb_num'=>' ',
                'comment'=>' ',
            ],
            //MDM
            [
                'name' => 'Gestion des Terminaux Mobiles (MDM)',
                'function' => 'MDM enables organizations to secure, monitor, and manage the use of mobile devices used by employees.',
                'version' => ' ',
                'editor' => ' ',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => '',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-07-29',
                'update_date' => '2024-07-29',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'Gestion des Terminaux Mobiles MDM',
                'category_id' => 7,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10,iOS,Android',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'MDM',
                'exe_file_path' => 'MDMSetup.exe',
                'complexity' => 'Simple',
                'criticite' => 'Moyen',
                'prerequis' => '',
                'created_at' => '2024-07-29',
                'euc'=>'Imad Aissouf',
                'kb_num'=>'KB0047262',
                'comment'=>' ',
            ],
            //POWERBI
            [
                'name' => 'PowerBI',
                'function' => 'Power BI allows users to visualize and share insights from their data. It provides interactive reports and dashboards to help users make data-driven decisions.',
                'version' => '2.129.905.0',
                'editor' => 'Microsoft',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0107017',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-06-07',
                'update_date' => '2024-06-07',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'Power BI',
                'category_id' => 3,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'Power BI',
                'exe_file_path' => 'BISetup.exe',
                'complexity' => 'Simple',
                'criticite' => 'Simple',
                'prerequis' => '',
                'created_at' => '2024-06-07',
                'euc'=>'Redouane Farik',
                'kb_num'=>'KB0043604',
                'comment'=>' ',
            ],
            //PLUGIN HOLOBUILDER POUR REVIT
            [
                'name' => 'Plugin Holobuilder pour Revit',
                'function' => 'Holobuilder Plugin for Revit is a tool designed to integrate Holobuilder\'s 360° image technology with Autodesk Revit, enabling seamless construction project documentation and virtual walkthroughs.',
                'version' => '2.9.3',
                'editor' => 'Holobuilder',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0106670',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-06-18',
                'update_date' => '2024-06-18',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'Plugin Holobuilder pour Revit',
                'category_id' => 5,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'Plugin Holobuilder pour Revit',
                'exe_file_path' => 'HolobuilderSetup.exe',
                'complexity' => 'Simple',
                'criticite' => 'Simple',
                'prerequis' => '',
                'created_at' => '2024-06-18',
                'euc'=>'Redouane Farik',
                'kb_num'=>'KB0044572',
                'comment'=>' ',
            ],
            //APPLE ITUNES
            [
                'name' => 'Apple itunes',
                'function' => 'Apple iTunes is a software application used for purchasing, organizing, and playing music and videos, as well as managing iPhone, iPad, and iPod touch devices. It serves as a digital storefront for purchasing content like music, movies, TV shows, and audiobooks from the iTunes Store. Additionally, iTunes provides services like syncing devices, backing up data, and managing media libraries.',
                'version' => '12.13.2.3',
                'editor' => 'Appel',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0107999',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-06-21',
                'update_date' => '2024-06-21',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'Apple itunes',
                'category_id' => 8,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10,iOS',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'Delinea Mobile',
                'exe_file_path' => 'DelineaSetup.exe',
                'complexity' => 'Simple',
                'criticite' => 'Simple',
                'prerequis' => 'Only iOS',
                'created_at' => '2024-06-21',
                'euc'=>'Redouane Farik',
                'kb_num'=>'KB0044186',
                'comment'=>' ',
            ],
            //ADOBE ACROBAT
            [
                'name' => 'Adobe Acrobat Reader DC',
                'function' => 'Adobe Acrobat Reader DC is a free and widely used software for viewing, printing, and annotating PDF files.',
                'version' => '2024.5.20320',
                'editor' => 'Adobe',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0116161',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-12-24',
                'update_date' => '2024-12-24',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'Adobe Acrobat Reader DC',
                'category_id' => 3,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10,iOS,Android',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'Adobe Acrobat Reader DC',
                'exe_file_path' => 'AdobeReaderSetup.exe',
                'complexity' => 'Simple',
                'criticite' => 'Simple',
                'prerequis' => '',
                'created_at' => '2024-06-18',
                'euc'=>'Redouane Farik',
                'kb_num'=>'KB0054299',
                'comment'=>' ',
            ],
            //REVIT
            [
                'name' => 'Revit',
                'function' => 'Autodesk Revit is a Building Information Modeling (BIM) software used for designing and managing building projects, particularly in the fields of architecture, engineering, and construction.',
                'version' => '2023_FR',
                'editor' => 'Autodesk',
                'qualification_statut' => 'En cours',
                'rfc_number' => 'RITM0108487',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-06-26',
                'update_date' => '2024-06-26',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'Revit',
                'category_id' => 5,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'Revit',
                'exe_file_path' => 'RevitSetup.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Simple',
                'prerequis' => '',
                'created_at' => '2024-06-26',
                'euc'=>'Redouane Farik',
                'kb_num'=>' ',
                'comment'=>'en attente de la création des Kbs',
            ],
            //DILIGENT
            [
                'name' => 'Diligent',
                'function' => 'Diligent Boards is a secure, cloud-based board management software that helps organizations streamline board and executive team operations. It provides digital solutions for preparing and organizing board meetings, sharing confidential documents, collaborating on governance, and ensuring compliance.',
                'version' => '4.0.0.4833',
                'editor' => 'Diligent Boards',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0109283',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-07-18',
                'update_date' => '2024-07-18',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'Diligent',
                'category_id' => 11,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'Diligent',
                'exe_file_path' => 'DiligentSetup.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Moyen',
                'prerequis' => '',
                'created_at' => '2024-07-18',
                'euc'=>'Redouane Farik',
                'kb_num'=>'KB0046732',
                'comment'=>' ',
            ],
            //Adobe Acrobat DC 
            [
                'name' => 'Adobe Acrobat DC',
                'function' => 'Adobe Acrobat DC is a paid, more advanced version of Acrobat that includes all the features of Acrobat Reader DC, along with additional tools for creating, editing, converting, and managing PDFs.',
                'version' => '2024.2.20759.0',
                'editor' => 'Adobe',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0107994',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-12-24',
                'update_date' => '2024-12-24',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'Adobe Acrobat DC',
                'category_id' => 3,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10,iOS,Android',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'Adobe Acrobat DC',
                'exe_file_path' => 'AdobeDCSetup.exe',
                'complexity' => 'Simple',
                'criticite' => 'Simple',
                'prerequis' => '',
                'created_at' => '2024-07-30',
                'euc'=>'Redouane Farik',
                'kb_num'=>'KB0047569',
                'comment'=>' ',
            ],
            //PLUG IN DISTEM
            [
                'name' => 'Plug-in DiStem de diroots pour revit-0.9.10',
                'function' => 'DiStem Plugin for Revit 0.9.10 is a software plugin designed for Autodesk Revit, developed by DiRoots. It provides various functionality to enhance the workflow within Revit, specifically aimed at improving the automation and management of BIM processes.',
                'version' => '0.9.10',
                'editor' => 'DiRoots',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0106053',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-10-06',
                'update_date' => '2024-10-06',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'Plug-in DiStem de diroots pour revit-0.9.10',
                'category_id' => 1,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'Plug-in DiStem de diroots',
                'exe_file_path' => 'DiRootsSetup.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Moyen',
                'prerequis' => '',
                'created_at' => '2024-10-06',
                'euc'=>'Zakaria EL IDRISSI',
                'kb_num'=>'KB0043668',
                'comment'=>' ',
            ],
            //NOTEPAD
            [
                'name' => 'Notepad++',
                'function' => 'Notepad++ is a free, open-source text and source code editor for Windows.',
                'version' => '8.6.5.0',
                'editor' => 'Team NotePad++',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0106883',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-06-21',
                'update_date' => '2024-06-21',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'Team Notepad++',
                'category_id' => 1,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'Notepad++',
                'exe_file_path' => 'NotepadSetup.exe',
                'complexity' => 'Simple',
                'criticite' => 'Simple',
                'prerequis' => '',
                'created_at' => '2024-06-21',
                'euc'=>'Zakaria EL IDRISSI',
                'kb_num'=>'KB0043903',
                'comment'=>' ',
            ],
            //7ZIP
            [
                'name' => '7ZIP',
                'function' => '7-Zip is a free, open-source file archiver software used for compressing and decompressing files.',
                'version' => '24.08',
                'editor' => 'IgorPavlov',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0112473; RITM0115093',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-10-03',
                'update_date' => '2024-10-03',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => '7ZIP - IgorPavlov',
                'category_id' => 3,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => '7ZIP',
                'exe_file_path' => '7ZipSetup.exe',
                'complexity' => 'Simple',
                'criticite' => 'Moyen',
                'prerequis' => '',
                'created_at' => '2024-06-21',
                'euc'=>'Zakaria EL IDRISSI',
                'kb_num'=>'KB0052591',
                'comment'=>' ',
            ],
            //UNIT CONVERT
            [
                'name' => 'Unit Convert',
                'function' => 'Unit Convert is designed to convert between various units of measurement, including length, weight, temperature, volume, and more.',
                'version' => '4.10',
                'editor' => 'Josh Madison',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0107684',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-06-25',
                'update_date' => '2024-06-25',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'Unit Convert',
                'category_id' => 3,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'Unit Convert',
                'exe_file_path' => 'UnitConvertSetup.exe',
                'complexity' => 'Simple',
                'criticite' => 'Simple',
                'prerequis' => '',
                'created_at' => '2024-06-25',
                'euc'=>'Zakaria EL IDRISSI',
                'kb_num'=>'KB0044683',
                'comment'=>' ',
            ],
            //OPEN STUDIO SDK
            [
                'name' => 'OpenStudio SDK (Full)',
                'function' => 'OpenStudio SDK provides a comprehensive set of core libraries and tools for energy modeling and building simulation. It includes functionalities to streamline the creation and analysis of energy models, focusing on efficiency and ease of integration with existing workflows',
                'version' => '3.8.0',
                'editor' => 'NREL',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0111208',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-06-25',
                'update_date' => '2024-06-25',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'OpenStudio SDK',
                'category_id' => 9,
                'service_id' => 9,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'OpenStudio SDK',
                'exe_file_path' => 'OpenStudioSetup.exe',
                'complexity' => 'Simple',
                'criticite' => 'Simple',
                'prerequis' => '',
                'created_at' => '2024-06-25',
                'euc'=>'Zakaria EL IDRISSI',
                'kb_num'=>'KB0052988',
                'comment'=>'Instructions provided by the requester are not functionnals, Requestor is informed by email',
            ],
            //AUTOCAD
            [
                'name' => 'AutoCAD',
                'function' => 'AutoCAD is a professional-grade design and drafting software. It allows users to create precise 2D and 3D drawings for architecture, engineering, construction, and manufacturing.',
                'version' => '2024_EN',
                'editor' => 'Autodesk',
                'qualification_statut' => 'En cours',
                'rfc_number' => 'RITM0108487',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-06-25',
                'update_date' => '2024-06-25',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'AutoCAD',
                'category_id' => 5,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'AutoCAD',
                'exe_file_path' => 'AutoCADSetup.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Moyen',
                'prerequis' => '',
                'created_at' => '2024-06-25',
                'euc'=>'Redouane Farik',
                'kb_num'=>'',
                'comment'=>'en attente de la création des Kbs',
            ],
            //AUTOCAD MAP 3D
            [
                'name' => 'AutoCAD_Map_3D',
                'function' => 'AutoCAD Map 3D is a specialized GIS and mapping software built on the core functionality of AutoCAD, it combines CAD tools with geographic information systems (GIS) capabilities, enabling users to create, analyze, and manage spatial data. It is ideal for infrastructure planning, utility management, and urban development projects.',
                'version' => '2024_EN',
                'editor' => 'Autodesk',
                'qualification_statut' => 'En cours',
                'rfc_number' => 'RITM0108487',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-06-25',
                'update_date' => '2024-06-25',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'AutoCAD',
                'category_id' => 9,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'AutoCAD3D',
                'exe_file_path' => 'AutoCAD3DSetup.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Moyen',
                'prerequis' => '',
                'created_at' => '2024-06-25',
                'euc'=>'Redouane Farik',
                'kb_num'=>'',
                'comment'=>'en attente de la création des Kbs',
            ],
            //CIVIL 3D
            [
                'name' => 'Civil_3D',
                'function' => 'Civil 3D is a civil engineering design and documentation software that supports Building Information Modeling (BIM) workflows.',
                'version' => '2024_EN',
                'editor' => 'Autodesk',
                'qualification_statut' => 'En cours',
                'rfc_number' => 'RITM0108487',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-06-25',
                'update_date' => '2024-06-25',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'Civil3D',
                'category_id' => 9,
                'service_id' => 9,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'Civil3D',
                'exe_file_path' => 'Civil3DSetup.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Moyen',
                'prerequis' => '',
                'created_at' => '2024-06-25',
                'euc'=>'Redouane Farik',
                'kb_num'=>'',
                'comment'=>'en attente de la création des Kbs',
            ],
            //RECAP PRO
            [
                'name' => 'ReCap_Pro',
                'function' => 'ReCap Pro is a reality capture and 3D scanning software for converting physical spaces into digital models. It supports point cloud creation, 3D modeling, and laser scanning.',
                'version' => '2024_FR',
                'editor' => 'Autodesk',
                'qualification_statut' => 'En cours',
                'rfc_number' => 'RITM0108487',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-06-25',
                'update_date' => '2024-06-25',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'ReCap_Pro',
                'category_id' => 9,
                'service_id' => 9,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'Francais',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'Recap_Pro',
                'exe_file_path' => 'RecapProSetup.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Moyen',
                'prerequis' => '',
                'created_at' => '2024-06-25',
                'euc'=>'Redouane Farik',
                'kb_num'=>'',
                'comment'=>'en attente de la création des Kbs',
            ],
            //INFRAWORKS
            [
                'name' => 'InfraWorks',
                'function' => 'InfraWorks is a 3D conceptual design and modeling software for civil infrastructure projects. It enables engineers and planners to create, analyze, and communicate design concepts in the context of the real world.',
                'version' => '2024_EN',
                'editor' => 'Autodesk',
                'qualification_statut' => 'En cours',
                'rfc_number' => 'RITM0108487',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-06-25',
                'update_date' => '2024-06-25',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'InfraWorks',
                'category_id' => 9,
                'service_id' => 9,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'InfraWorks',
                'exe_file_path' => 'InfraWorksSetup.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Moyen',
                'prerequis' => '',
                'created_at' => '2024-06-25',
                'euc'=>'Redouane Farik',
                'kb_num'=>'',
                'comment'=>'en attente de la création des Kbs',
            ],
            //FORMIT PRO
            [
                'name' => 'Formit_PRO',
                'function' => 'Formit_PRO is a 3D sketching tool designed for architects and designers. It allows users to conceptualize and develop design ideas while integrating with other Autodesk tools for advanced analysis and modeling.',
                'version' => '2024_EN',
                'editor' => 'Autodesk',
                'qualification_statut' => 'En cours',
                'rfc_number' => 'RITM0108487',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-06-25',
                'update_date' => '2024-06-25',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'Formit_PRO',
                'category_id' => 5,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'Formit PRO',
                'exe_file_path' => 'FormitPROSetup.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Moyen',
                'prerequis' => '',
                'created_at' => '2024-06-25',
                'euc'=>'Redouane Farik',
                'kb_num'=>'',
                'comment'=>'en attente de la création des Kbs',
            ],
            //VEHICLE TRACKING
            [
                'name' => 'Vehicle_Tracking',
                'function' => 'Vehicle Tracking is a software for transportation analysis and simulation. It helps in assessing vehicle movements on roads and intersections, aiding in road design and transportation planning.',
                'version' => '2024_EN',
                'editor' => 'Autodesk',
                'qualification_statut' => 'En cours',
                'rfc_number' => 'RITM0108487',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-06-25',
                'update_date' => '2024-06-25',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'Vehicle Tracking',
                'category_id' => 9,
                'service_id' => 9,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'Vehicle_Tracking',
                'exe_file_path' => 'VehicleTrackingSetup.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Moyen',
                'prerequis' => '',
                'created_at' => '2024-06-25',
                'euc'=>'Redouane Farik',
                'kb_num'=>'',
                'comment'=>'en attente de la création des Kbs',
            ],
            //DESKTOP CONNECTOR
            [
                'name' => 'Desktop_Connector',
                'function' => 'Desktop Connector is a tool that bridges cloud storage (Autodesk Construction Cloud or BIM 360) with desktop workflows, enabling users to sync, access, and manage files directly from their local devices.',
                'version' => '2024_EN',
                'editor' => 'Autodesk',
                'qualification_statut' => 'En cours',
                'rfc_number' => 'RITM0108487',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-06-25',
                'update_date' => '2024-06-25',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'Desktop_Connector',
                'category_id' => 3,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'Desktop_Connector',
                'exe_file_path' => 'DesktopConnectorSetup.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Moyen',
                'prerequis' => '',
                'created_at' => '2024-06-25',
                'euc'=>'Redouane Farik',
                'kb_num'=>'',
                'comment'=>'en attente de la création des Kbs',
            ],
            //NAVISWORKS MANAGE
            [
                'name' => 'Navisworks_Manage',
                'function' => 'Navisworks Manage is a project review software used for BIM coordination, clash detection, and construction simulation. It helps teams identify and resolve design issues before construction begins.',
                'version' => '2024_FR',
                'editor' => 'Autodesk',
                'qualification_statut' => 'En cours',
                'rfc_number' => 'RITM0108487',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-06-25',
                'update_date' => '2024-06-25',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'Navisworks Manage',
                'category_id' => 9,
                'service_id' => 9,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'Francais',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'Navisworks_Manage',
                'exe_file_path' => 'NavisworksManageSetup.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Moyen',
                'prerequis' => '',
                'created_at' => '2024-06-25',
                'euc'=>'Redouane Farik',
                'kb_num'=>'',
                'comment'=>'en attente de la création des Kbs',
            ],
            //VAULT PROFESSIONAL CLIENT
            [
                'name' => 'Vault_Professional_Client',
                'function' => 'Vault Professional Client is a data management software that helps design and engineering teams organize, manage, and track their CAD files, documents, and revisions in a secure and centralized environment.',
                'version' => '2024_EN',
                'editor' => 'Autodesk',
                'qualification_statut' => 'En cours',
                'rfc_number' => 'RITM0108487',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-06-25',
                'update_date' => '2024-06-25',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'Vault Professional Client',
                'category_id' => 4,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'Vault_Professional_Client',
                'exe_file_path' => 'Vault_Professional_ClientSetup.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Moyen',
                'prerequis' => '',
                'created_at' => '2024-06-25',
                'euc'=>'Redouane Farik',
                'kb_num'=>'',
                'comment'=>'en attente de la création des Kbs',
            ],
            
            //MS ACCESS
            [
                'name' => 'MS Access',
                'function' => 'Microsoft Access is a desktop relational database management system that provides users with tools to create, manage, and analyze databases.',
                'version' => '2016 (64 Bit)',
                'editor' => 'Microsoft',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0112125',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-04-24',
                'update_date' => '2024-04-24',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'Microsoft - MS Access',
                'category_id' => 4,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => true,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'MS Access',
                'exe_file_path' => 'MSAccessSetup.exe',
                'complexity' => 'Simple',
                'criticite' => 'Simple',
                'prerequis' => '',
                'created_at' => '2024-04-24',
                'euc'=>'Zakaria EL IDRISSI',
                'kb_num'=>'KB0052405',
                'comment'=>' ',
            ],
            
            //EDGE WEBVIEW2
            [
                'name' => 'Edge WebView2 Runtime',
                'function' => 'Edge WebView2 Runtime is a technology solution that allows you to embed web content in applications using the Microsoft Edge (Chromium) engine.',
                'version' => '109.0.1518.140',
                'editor' => 'Microsoft',
                'qualification_statut' => 'En cours',
                'rfc_number' => 'RITM0112364',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-04-24',
                'update_date' => '2024-04-24',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'Edge WebView2 Runtime',
                'category_id' => 1,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10,Android',
                'languages' => 'English',
                'master_integration' => true,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'Edge WebView2 Runtime',
                'exe_file_path' => 'Edge_WebView2_RuntimeSetup.exe',
                'complexity' => 'Simple',
                'criticite' => 'Simple',
                'prerequis' => 'Windows 10 version 1809 or later.',
                'created_at' => '2024-04-24',
                'euc'=>'Zakaria EL IDRISSI',
                'kb_num'=>'',
                'comment'=>' ',
            ],
            //RETSCREEN EXPERT
            [
                'name' => 'RETScreen Expert',
                'function' => 'RETScreen Expert is a software solution designed for professionals in the energy management and renewable energy sectors. It provides tools for assessing the viability, performance, and financial analysis of energy projects, including renewable energy technologies and energy efficiency measures.',
                'version' => '9.1.0.98 ',
                'editor' => '',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0112683',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-01-01',
                'update_date' => '2024-01-01',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'RETScreen Expert',
                'category_id' => 9,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => true,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'RETScreen Expert',
                'exe_file_path' => 'RETScreenExpertSetup.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Complexe',
                'prerequis' => '',
                'created_at' => '2024-06-25',
                'euc'=>'Redouane Farik',
                'kb_num'=>'KB0052681',
                'comment'=>' ',
            ],
            //CONFIG TOOL
            [
                'name' => 'Delinea Secret Server Mobile',
                'function' => 'Delinea Secret Server Mobile is a mobile application that provides secure access to a Secret Server instance to view, manage and use secrets stored there. It offers useful functionality including multi-factor authentication, biometric authentication, autofill, online and offline caching, and advanced secret workflows.',
                'version' => '1.00',
                'editor' => 'IOS - Android',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0104954',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-04-24',
                'update_date' => '2024-04-24',
                'responsable_cit' => ' ',
                'adm' => ' ',
                'mot_clef' => 'IOS-Android',
                'category_id' => 7,
                'service_id' => 1,
                'os_compatibility' => 'Android',
                'languages' => 'English',
                'master_integration' => true,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'Delinea Mobile',
                'exe_file_path' => 'DelineaSetup.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Complexe',
                'prerequis' => 'iOS 12.0 or Android 8.0 or later.
                Access to a Delinea Secret Server instance.',
                'created_at' => '2024-04-24',
                'euc'=>'Ahmad Amine EL AOURI',
                'kb_num'=>'KB0043829',
                'comment'=>' ',
            ],
            //ANOMS
            [
                'name' => 'ANOMS',
                'function' => 'ANOMS is a software solution used for managing and monitoring various network security systems.',
                'version' => 'N/A',
                'editor' => 'N/A',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0113015',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-10-18',
                'update_date' => '2024-10-18',
                'responsable_cit' => 'Redouane Farik',
                'adm' => 'SCCM',
                'mot_clef' => 'ANOMS - Security',
                'category_id' => 7,
                'service_id' => 8,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => true,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 60,
                'arp_full_name' => 'ANOMS',
                'exe_file_path' => 'ANOMS_installer.exe',
                'complexity' => 'Complexe',
                'criticite' => 'Complexe',
                'prerequis' => 'Windows OS, Network Security System Access',
                'created_at' => '2024-10-18',
                'euc' => 'Redouane Farik',
                'kb_num' => 'KB0052875',
                'comment' => 'N/A',
            ],
            
            //PLUGIN BRIEFCAM
            [
                'name' => 'plugin BriefCam',
                'function' => 'BriefCam Plugin is a video analytics tool for surveillance systems.',
                'version' => '7.00',
                'editor' => 'N/A',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0114575',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-12-02',
                'update_date' => '2024-12-02',
                'responsable_cit' => 'Ahmad Amine EL AOURI',
                'adm' => 'SCCM',
                'mot_clef' => 'Video Analytics, Surveillance - plugin BriefCam',
                'category_id' => 7,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => true,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 50,
                'arp_full_name' => 'BriefCam Plugin',
                'exe_file_path' => 'BriefCamPlugin_installer.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Moyen',
                'prerequis' => 'Windows OS, Surveillance System Access',
                'created_at' => '2024-12-02',
                'euc' => 'Ahmad Amine EL AOURI',
                'kb_num' => 'KB0053622',
                'comment' => 'N/A',
            ],
            //BLUEBEAM
            [
                'name' => 'BlueBeam',
                'function' => 'BlueBeam is a software tool for creating, editing, and managing PDF documents, often used for construction and design.',
                'version' => '21.3.0',
                'editor' => 'N/A',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0114743',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-11-28',
                'update_date' => '2024-11-28',
                'responsable_cit' => 'Zakaria EL IDRISSI',
                'adm' => 'SCCM',
                'mot_clef' => 'PDF Management, Construction, Design, BlueBeam',
                'category_id' => 3,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'English',
                'master_integration' => true,
                'type' => 'isolé',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 60,
                'arp_full_name' => 'BlueBeam',
                'exe_file_path' => 'BlueBeam_installer.exe',
                'complexity' => 'Complexe',
                'criticite' => 'Complexe',
                'prerequis' => 'Windows OS, PDF Management Tools',
                'created_at' => '2024-11-28',
                'euc' => 'Zakaria EL IDRISSI',
                'kb_num' => 'KB0053373',
                'comment' => 'N/A',
            ],
            //CISCO
            [
                'name' => 'Cisco Jabber',
                'function' => 'Cisco Jabber is a communication tool for messaging, video conferencing, and collaboration.',
                'version' => '15.00',
                'editor' => 'Cisco',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0115028',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-11-21',
                'update_date' => '2024-11-21',
                'responsable_cit' => 'Ahmad Amine EL AOURI',
                'adm' => 'SCCM',
                'mot_clef' => 'Communication, Collaboration, CISCO Jabber',
                'category_id' => 8,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10,Android,iOS',
                'languages' => 'Francais, Anglais',
                'master_integration' => true,
                'type' => 'isolé',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 40,
                'arp_full_name' => 'Cisco Jabber',
                'exe_file_path' => 'CiscoJabber_installer.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Moyen',
                'prerequis' => 'Windows OS, Internet connection',
                'created_at' => '2024-11-21',
                'euc' => 'Ahmad Amine EL AOURI',
                'kb_num' => 'KB0053396',
                'comment' => 'N/A',
            ],
            //SAP LOGON
            [
                'name' => 'SAP Logon',
                'function' => 'SAP Logon is a client application used to log into SAP environments.',
                'version' => '800 SP10',
                'editor' => 'SAP',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0114879',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-11-22',
                'update_date' => '2024-11-22',
                'responsable_cit' => 'Zakaria EL IDRISSI',
                'adm' => 'SCCM',
                'mot_clef' => 'SAP, Client Application, Logon',
                'category_id' => 3,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'Francais, Anglais',
                'master_integration' => true,
                'type' => 'isolé',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'SAP Logon',
                'exe_file_path' => 'SAPLogon_installer.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Moyen',
                'prerequis' => 'Windows OS, SAP System Access',
                'created_at' => '2024-11-22',
                'euc' => 'Zakaria EL IDRISSI',
                'kb_num' => 'KB0053786',
                'comment' => 'N/A',
            ],
            //VISUAL STUDIO CODE
            [
                'name' => 'Visual Studio Code',
                'function' => 'Visual Studio Code is a code editor supporting multiple programming languages.',
                'version' => '1.96.1',
                'editor' => 'Microsoft',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0116070',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-12-19',
                'update_date' => '2024-12-19',
                'responsable_cit' => 'Zakaria EL IDRISSI',
                'adm' => 'SCCM',
                'mot_clef' => 'Code Editor, Development, Visual Studio Code',
                'category_id' => 1,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'Anglais, Francais',
                'master_integration' => true,
                'type' => 'isolé',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 30,
                'arp_full_name' => 'Visual Studio Code',
                'exe_file_path' => 'VSCode_installer.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Moyen',
                'prerequis' => 'Windows OS, Internet connection',
                'created_at' => '2024-12-19',
                'euc' => 'Zakaria EL IDRISSI',
                'kb_num' => 'KB0053938',
                'comment' => 'N/A',
            ],
            //HONEYWELL EBI
            [
                'name' => 'Honeywell EBI',
                'function' => 'Honeywell EBI is an energy management and control system for optimizing building operations.',
                'version' => 'N/A',
                'editor' => 'N/A',
                'qualification_statut' => 'En cours',
                'rfc_number' => 'RITM0115432',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-12-18',
                'update_date' => '2024-12-18',
                'responsable_cit' => 'Redouane Farik',
                'adm' => 'SCCM',
                'mot_clef' => 'Honeywell EBI',
                'category_id' => 3,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'Anglais',
                'master_integration' => true,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 60,
                'arp_full_name' => 'Honeywell EBI',
                'exe_file_path' => 'EBI_installer.exe',
                'complexity' => 'Complexe',
                'criticite' => 'Complexe',
                'prerequis' => 'Windows OS, Honeywell EBI System Access',
                'created_at' => '2024-12-18',
                'euc' => 'Redouane Farik',
                'kb_num' => 'N/A',
                'comment' => 'N/A',
            ],
            //CERTIFIO
            [
                'name' => 'CertifiO Suite (Notarius ConsignO Desktop)',
                'function' => 'CertifiO Suite is used for digital document signing and notarization.',
                'version' => '3.9.1',
                'editor' => 'N/A',
                'qualification_statut' => 'Qualifié',
                'rfc_number' => 'RITM0115111',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-12-18',
                'update_date' => '2024-12-18',
                'responsable_cit' => 'Redouane Farik',
                'adm' => 'SCCM',
                'mot_clef' => 'Digital Signing, CertifiO Suite (Notarius ConsignO Desktop)',
                'category_id' => 7,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10',
                'languages' => 'Francais, Anglais',
                'master_integration' => true,
                'type' => 'isolé',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 45,
                'arp_full_name' => 'CertifiO Suite',
                'exe_file_path' => 'CertifiO_Suite_installer.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Complexe',
                'prerequis' => 'Windows OS, CertifiO Suite Access',
                'created_at' => '2024-12-18',
                'euc' => 'Redouane Farik',
                'kb_num' => 'KB0053871',
                'comment' => 'N/A',
            ],
        ]);
    }
}
