<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\TechSol;
use Illuminate\Support\Facades\DB;

class TechSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //DB::table('techsols')->truncate();
        DB::statement('ALTER TABLE techsols AUTO_INCREMENT = 1;');
        DB::table('techsols')->insert([
            //MDM
            [
                'name' => 'Gestion des Terminaux Mobiles (MDM)',
                'support_informations' => 'MDM enables organizations to secure, monitor, and manage the use of mobile devices used by employees.',
                'version' => 'null',
                'editor' => 'null',
                'qualification_statut' => 'Qualified',
                'rfc_number' => 'null',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-07-29',
                'update_date' => '2024-07-29',
                'responsable_cit' => 'Imad Aissouf',
                'adm' => 'Imad Aissouf',
                'mot_clef' => 'Gestion des Terminaux Mobiles MDM',
                'category_id' => 7,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10,iOS,Android',
                'languages' => 'Francais, Anglais',
                'master_integration' => false,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 2,
                'arp_full_name' => 'MDM',
                'exe_file_path' => 'MDMSetup.exe',
                'complexity' => 'Simple',
                'criticite' => 'Moyen',
                'prerequis' => 'null',
                'created_at' => '2024-07-29',
                'euc'=>'Imad Aissouf',
                'kb_num'=>'KB0047262',
                'comment'=>'null',
            ],
            //A1244A S DEPLOIEMENT DU THEME
            [
                'name' => 'A1244A - S/4HANA  -Déploiement du thème Quartz - sans l option Fiori.',
                'support_informations' => 'S/4HANA is an advanced ERP system designed to run on the SAP HANA in-memory database. The deployment of the Quartz theme enhances the user interface, providing a modernized, consistent design across applications.',
                'version' => 'null',
                'editor' => 'SAP',
                'qualification_statut' => 'Qualified',
                'rfc_number' => 'RITM0110387',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-06-25',
                'update_date' => '2024-06-25',
                'responsable_cit' => 'Zakaria EL IDRISSI',
                'adm' => 'Zakaria EL IDRISSI',
                'mot_clef' => 'A1244A - S/4HANA  -Déploiement du thème Quartz - sans l option Fiori.',
                'category_id' => 4,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11, Windows 10',
                'languages' => 'Francais, Anglais',
                'master_integration' => true,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 2,
                'arp_full_name' => 'S/4HANA',
                'exe_file_path' => 'S/4HANASetup.exe',
                'complexity' => 'Moyen',
                'criticite' => 'Moyen',
                'prerequis' => 'null',
                'created_at' => '2024-06-25',
                'euc'=>'Zakaria EL IDRISSI',
                'kb_num'=>'KB0051517',
                'comment'=>'null',
            ],
            //MODIFT TS
            [
                'name' => 'Modify TS : Content Player 5.4 par le Content Player 6.4.',
                'support_informations' => 'Content Player software designed to manage and play multimedia content for digital signage applications, replacing version 5.4 with version 6.4 for enhanced features.',
                'version' => '6.4',
                'editor' => 'Content Player',
                'qualification_statut' => 'Qualified',
                'rfc_number' => 'RITM0112101',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-10-09',
                'update_date' => '2024-10-09',
                'responsable_cit' => 'Redouane Farik',
                'adm' => 'Redouane Farik',
                'mot_clef' => 'Content Player 6.4',
                'category_id' => 8,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10,Android',
                'languages' => 'Francais, Anglais',
                'master_integration' => true,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 2,
                'arp_full_name' => 'Content Player 6.4',
                'exe_file_path' => 'ContentPlayer6_4Setup.exe',
                'complexity' => 'Simple',
                'criticite' => 'Simple',
                'prerequis' => 'null',
                'created_at' => '2024-10-09',
                'euc'=>'Redouane Farik',
                'kb_num'=>'KB0043827',
                'comment'=>'null',
            ],
            //script pour modifier la clé de registre "SecurityLevel" pour désactiver le statut de sécurité dans SAP Logon
            [
                'name' => 'script pour modifier la clé de registre "SecurityLevel" pour désactiver le statut de sécurité dans SAP Logon',
                'support_informations' => 'This script modifies the Windows registry to adjust the SecurityLevel key, disabling certain security statuses in SAP Logon.',
                'version' => '6.4',
                'editor' => 'Content Player',
                'qualification_statut' => 'Qualified',
                'rfc_number' => 'RITM0112101',
                'end_of_life' => '2050-01-01',
                'qualification_date' => '2024-10-09',
                'update_date' => '2024-10-09',
                'responsable_cit' => 'Redouane Farik',
                'adm' => 'Redouane Farik',
                'mot_clef' => 'Content Player 6.4',
                'category_id' => 8,
                'service_id' => 1,
                'os_compatibility' => 'Windows 11/10,Android',
                'languages' => 'Francais, Anglais',
                'master_integration' => true,
                'type' => 'courant',
                'method_installation' => 'auto',
                'source' => 'Software Center',
                'sms' => false,
                'time_insta' => 2,
                'arp_full_name' => 'Content Player 6.4',
                'exe_file_path' => 'ContentPlayer6_4Setup.exe',
                'complexity' => 'Simple',
                'criticite' => 'Simple',
                'prerequis' => 'null',
                'created_at' => '2024-10-09',
                'euc'=>'Redouane Farik',
                'kb_num'=>'KB0043827',
                'comment'=>'null',
            ],
        ]);
    }
}
